name: Master
on:
  push:
    branches:
      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  prerelease:
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "16"
        cache: "yarn"

    - name: install deps
      run: |
        yarn install --immutable | grep -v 'YN0013'

    - name: build:release
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        GH_RELEASE_GITHUB_API_TOKEN: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn build:release

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: packages/app/build

    - name: Deploy prerelease
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST }}
        port: 22
        key: ${{ secrets.KEY }}
        source: ${{ github.workspace }}/packages/app/build
        target: "/home/ubuntu/credential-interface"
        strip_components: 5
        rm: true

  release:
    if: "startsWith(github.event.head_commit.message, '[CI Skip] release/stable')"
    runs-on: ubuntu-latest
    environment: master
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GH_PAT }}

    - name: install deps
      run: |
        yarn install --immutable | grep -v 'YN0013'

    - name: build
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn build

    - name: Deploy release
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST }}
        port: 22
        key: ${{ secrets.KEY }}
        source: ${{ github.workspace }}/packages/app/build
        target: "/home/ubuntu/credential-interface"
        strip_components: 5
        rm: true

gh_pages:
  environment:
    name: github-pages
    url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v1
