name: Master
on:
  push:
    branches:
      - master

jobs:
  prerelease:
    name: ${{ matrix.step }}
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    environment: dev
    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: |
        yarn install --immutable | grep -v 'YN0013'

    - name: ${{ matrix.step }}
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn build:release

    - name: Deploy prerelease
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST }}
        port: 22
        key: ${{ secrets.KEY }}
        source: ${{ github.workspace }}/packages/app/build
        target: "/home/ubuntu/credential-interface"
        strip_components: 5
        rm: true

  release:
    needs: prerelease
    if: "! startsWith(github.event.head_commit.message, '[CI Skip]')"
    runs-on: ubuntu-latest
    environment: master
    steps:
    - uses: actions/checkout@v2

    - name: Get version
      id: version
      uses: martinbeentjes/npm-get-version-action@master

    - name: Deploy release
      if: "! contains(steps.version.outputs.current-version, '-')"
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST }}
        port: 22
        key: ${{ secrets.KEY }}
        source: ${{ github.workspace }}/packages/app/build
        target: "/home/ubuntu/credential-interface"
        strip_components: 5
        rm: true
